-- CreateEnum
CREATE TYPE "Meses" AS ENUM ('JANEIRO', 'FEVEREIRO', 'MARCO', 'ABRIL', 'MAIO', 'JUNHO', 'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO');

-- CreateTable
CREATE TABLE "Metas" (
    "id" TEXT NOT NULL,
    "produto" TEXT NOT NULL DEFAULT '',
    "metaProduto" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "codRep" INTEGER NOT NULL DEFAULT 0,
    "mesMeta" INTEGER NOT NULL DEFAULT 0,
    "anoMeta" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Metas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CalendarioMetas" (
    "id" TEXT NOT NULL,
    "mes" "Meses" NOT NULL DEFAULT 'JANEIRO',
    "ano" INTEGER NOT NULL DEFAULT 2025,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CalendarioMetas_pkey" PRIMARY KEY ("id")
);
