import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { mapGroupQuoteLines } from "../../../../../src/features/overviewCustomer/sync/OverviewCustomerGroupQuotesSeniorQuery";

describe("mapGroupQuoteLines", () => {
  it("keeps two item lines from the same order without aggregating values", () => {
    const lines = mapGroupQuoteLines([
      {
        DATA: "2026-09-09",
        NUMPED: 100,
        SITUACAO: 9,
        CODREP: 10,
        APEREP: "Rep A",
        CODCLI: 200,
        FANTASIA: "Cliente A",
        NOME_PRO: "Produto 1",
        CODPRO: "P001",
        CODGRP: "G030",
        IPI: 1,
        ICM: 2,
        ICMS: 12,
        QTDPED: 2,
        PREUNI: 10,
        VLRFINAL: 20,
        MARGEM_LUCRO: 5,
        PRE_CUSTO: 8,
        FRETE: 1.5,
        TRANSPORTADORA: 99,
        INCLUSO: "S",
      },
      {
        DATA: "2026-09-09",
        NUMPED: 100,
        SITUACAO: 5,
        CODREP: 10,
        APEREP: "Rep A",
        CODCLI: 200,
        FANTASIA: "Cliente A",
        NOME_PRO: "Produto 2",
        CODPRO: "P002",
        CODGRP: "G030",
        IPI: 3,
        ICM: 4,
        ICMS: 18,
        QTDPED: 1,
        PREUNI: 30,
        VLRFINAL: 30,
        MARGEM_LUCRO: 7,
        PRE_CUSTO: 20,
        FRETE: 2.5,
        TRANSPORTADORA: 88,
        INCLUSO: "N",
      },
    ]);

    assert.equal(lines.length, 2);
    assert.deepStrictEqual(lines[0], {
      datemi: "2026-09-09",
      numped: 100,
      sitped: 9,
      codRep: 10,
      aperep: "Rep A",
      codcli: 200,
      apecli: "Cliente A",
      productName: "Produto 1",
      codpro: "P001",
      codgrp: "G030",
      ipi: 1,
      icm: 2,
      icmsPercent: 12,
      qtdped: 2,
      preuni: 10,
      vlrfinal: 20,
      margem: 5,
      preCusto: 8,
      frete: 1.5,
      transportadora: 99,
      freteIncluso: true,
    });
    assert.deepStrictEqual(lines[1], {
      datemi: "2026-09-09",
      numped: 100,
      sitped: 5,
      codRep: 10,
      aperep: "Rep A",
      codcli: 200,
      apecli: "Cliente A",
      productName: "Produto 2",
      codpro: "P002",
      codgrp: "G030",
      ipi: 3,
      icm: 4,
      icmsPercent: 18,
      qtdped: 1,
      preuni: 30,
      vlrfinal: 30,
      margem: 7,
      preCusto: 20,
      frete: 2.5,
      transportadora: 88,
      freteIncluso: false,
    });
  });
});
